
interface _GlobalComponents {
      'AboutHeader': typeof import("../components/About/Header.vue")['default']
    'AboutIntro': typeof import("../components/About/Intro.vue")['default']
    'AboutJourney': typeof import("../components/About/Journey.vue")['default']
    'BlogBlogs': typeof import("../components/Blog/Blogs.vue")['default']
    'BlogDetailsAuthorArea': typeof import("../components/Blog/Details/AuthorArea.vue")['default']
    'BlogDetailsCommentsForm': typeof import("../components/Blog/Details/CommentsForm.vue")['default']
    'BlogDetailsContent': typeof import("../components/Blog/Details/Content.vue")['default']
    'BlogDetails': typeof import("../components/Blog/Details/Details.vue")['default']
    'BlogDetailsHeader': typeof import("../components/Blog/Details/Header.vue")['default']
    'BlogDetailsInfoArea': typeof import("../components/Blog/Details/InfoArea.vue")['default']
    'BlogDetailsNextPrev': typeof import("../components/Blog/Details/NextPrev.vue")['default']
    'BlogHeader': typeof import("../components/Blog/Header.vue")['default']
    'CommonCursor': typeof import("../components/Common/Cursor.vue")['default']
    'CommonFooter1': typeof import("../components/Common/Footer1.vue")['default']
    'CommonFooter2': typeof import("../components/Common/Footer2.vue")['default']
    'CommonLoader': typeof import("../components/Common/Loader.vue")['default']
    'CommonMenu': typeof import("../components/Common/Menu.vue")['default']
    'CommonNavbar': typeof import("../components/Common/Navbar.vue")['default']
    'CommonProgressScroll': typeof import("../components/Common/ProgressScroll.vue")['default']
    'ContactForm': typeof import("../components/Contact/Form.vue")['default']
    'ContactHeader': typeof import("../components/Contact/Header.vue")['default']
    'ContactInfo': typeof import("../components/Contact/Info.vue")['default']
    'CreativePortfolioBlog': typeof import("../components/CreativePortfolio/Blog.vue")['default']
    'CreativePortfolioContact': typeof import("../components/CreativePortfolio/Contact.vue")['default']
    'CreativePortfolioHeader': typeof import("../components/CreativePortfolio/Header.vue")['default']
    'CreativePortfolioMarquee': typeof import("../components/CreativePortfolio/Marquee.vue")['default']
    'CreativePortfolioTestimonials': typeof import("../components/CreativePortfolio/Testimonials.vue")['default']
    'HomeAbout': typeof import("../components/Home/About.vue")['default']
    'HomeAwards': typeof import("../components/Home/Awards.vue")['default']
    'HomeContact': typeof import("../components/Home/Contact.vue")['default']
    'HomeHeader': typeof import("../components/Home/Header.vue")['default']
    'HomeServices': typeof import("../components/Home/Services.vue")['default']
    'HomeTeam': typeof import("../components/Home/Team.vue")['default']
    'HomeTestimonials': typeof import("../components/Home/Testimonials.vue")['default']
    'HomeWorks': typeof import("../components/Home/Works.vue")['default']
    'LandingAbout': typeof import("../components/Landing/About.vue")['default']
    'LandingAccordions': typeof import("../components/Landing/Accordions.vue")['default']
    'LandingBlog': typeof import("../components/Landing/Blog.vue")['default']
    'LandingBrands': typeof import("../components/Landing/Brands.vue")['default']
    'LandingContact': typeof import("../components/Landing/Contact.vue")['default']
    'LandingHeader': typeof import("../components/Landing/Header.vue")['default']
    'LandingMarquee': typeof import("../components/Landing/Marquee.vue")['default']
    'LandingWorks': typeof import("../components/Landing/Works.vue")['default']
    'PortfolioCarouselSlider': typeof import("../components/Portfolio/CarouselSlider.vue")['default']
    'PortfolioFixedText': typeof import("../components/Portfolio/FixedText.vue")['default']
    'PortfolioGrid': typeof import("../components/Portfolio/Grid.vue")['default']
    'PortfolioGridClassic': typeof import("../components/Portfolio/GridClassic.vue")['default']
    'PortfolioHeader': typeof import("../components/Portfolio/Header.vue")['default']
    'PortfolioInteractiveInline': typeof import("../components/Portfolio/InteractiveInline.vue")['default']
    'PortfolioInteractiveVertical': typeof import("../components/Portfolio/InteractiveVertical.vue")['default']
    'PreviewFooter': typeof import("../components/Preview/Footer.vue")['default']
    'PreviewHeader': typeof import("../components/Preview/Header.vue")['default']
    'PreviewNavigation': typeof import("../components/Preview/Navigation.vue")['default']
    'PreviewPortfolio': typeof import("../components/Preview/Portfolio.vue")['default']
    'ProjectFourBottomContent': typeof import("../components/Project/Four/BottomContent.vue")['default']
    'ProjectFourBottomImage': typeof import("../components/Project/Four/BottomImage.vue")['default']
    'ProjectFourHeader': typeof import("../components/Project/Four/Header.vue")['default']
    'ProjectFourImageColumn': typeof import("../components/Project/Four/ImageColumn.vue")['default']
    'ProjectFourNextProject': typeof import("../components/Project/Four/NextProject.vue")['default']
    'ProjectFourTopContent': typeof import("../components/Project/Four/TopContent.vue")['default']
    'ProjectOneBottomContent': typeof import("../components/Project/One/BottomContent.vue")['default']
    'ProjectOneHeader': typeof import("../components/Project/One/Header.vue")['default']
    'ProjectOneNextProject': typeof import("../components/Project/One/NextProject.vue")['default']
    'ProjectOneTopContent': typeof import("../components/Project/One/TopContent.vue")['default']
    'ProjectOneWorks': typeof import("../components/Project/One/Works.vue")['default']
    'ProjectThreeBottomContent': typeof import("../components/Project/Three/BottomContent.vue")['default']
    'ProjectThreeBottomImage': typeof import("../components/Project/Three/BottomImage.vue")['default']
    'ProjectThreeHeader': typeof import("../components/Project/Three/Header.vue")['default']
    'ProjectThreeImageColumn': typeof import("../components/Project/Three/ImageColumn.vue")['default']
    'ProjectThreeNextProject': typeof import("../components/Project/Three/NextProject.vue")['default']
    'ProjectThreeTopContent': typeof import("../components/Project/Three/TopContent.vue")['default']
    'ProjectTwoBottomContent': typeof import("../components/Project/Two/BottomContent.vue")['default']
    'ProjectTwoHeader': typeof import("../components/Project/Two/Header.vue")['default']
    'ProjectTwoNextProject': typeof import("../components/Project/Two/NextProject.vue")['default']
    'ProjectTwoTopContent': typeof import("../components/Project/Two/TopContent.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyAboutHeader': typeof import("../components/About/Header.vue")['default']
    'LazyAboutIntro': typeof import("../components/About/Intro.vue")['default']
    'LazyAboutJourney': typeof import("../components/About/Journey.vue")['default']
    'LazyBlogBlogs': typeof import("../components/Blog/Blogs.vue")['default']
    'LazyBlogDetailsAuthorArea': typeof import("../components/Blog/Details/AuthorArea.vue")['default']
    'LazyBlogDetailsCommentsForm': typeof import("../components/Blog/Details/CommentsForm.vue")['default']
    'LazyBlogDetailsContent': typeof import("../components/Blog/Details/Content.vue")['default']
    'LazyBlogDetails': typeof import("../components/Blog/Details/Details.vue")['default']
    'LazyBlogDetailsHeader': typeof import("../components/Blog/Details/Header.vue")['default']
    'LazyBlogDetailsInfoArea': typeof import("../components/Blog/Details/InfoArea.vue")['default']
    'LazyBlogDetailsNextPrev': typeof import("../components/Blog/Details/NextPrev.vue")['default']
    'LazyBlogHeader': typeof import("../components/Blog/Header.vue")['default']
    'LazyCommonCursor': typeof import("../components/Common/Cursor.vue")['default']
    'LazyCommonFooter1': typeof import("../components/Common/Footer1.vue")['default']
    'LazyCommonFooter2': typeof import("../components/Common/Footer2.vue")['default']
    'LazyCommonLoader': typeof import("../components/Common/Loader.vue")['default']
    'LazyCommonMenu': typeof import("../components/Common/Menu.vue")['default']
    'LazyCommonNavbar': typeof import("../components/Common/Navbar.vue")['default']
    'LazyCommonProgressScroll': typeof import("../components/Common/ProgressScroll.vue")['default']
    'LazyContactForm': typeof import("../components/Contact/Form.vue")['default']
    'LazyContactHeader': typeof import("../components/Contact/Header.vue")['default']
    'LazyContactInfo': typeof import("../components/Contact/Info.vue")['default']
    'LazyCreativePortfolioBlog': typeof import("../components/CreativePortfolio/Blog.vue")['default']
    'LazyCreativePortfolioContact': typeof import("../components/CreativePortfolio/Contact.vue")['default']
    'LazyCreativePortfolioHeader': typeof import("../components/CreativePortfolio/Header.vue")['default']
    'LazyCreativePortfolioMarquee': typeof import("../components/CreativePortfolio/Marquee.vue")['default']
    'LazyCreativePortfolioTestimonials': typeof import("../components/CreativePortfolio/Testimonials.vue")['default']
    'LazyHomeAbout': typeof import("../components/Home/About.vue")['default']
    'LazyHomeAwards': typeof import("../components/Home/Awards.vue")['default']
    'LazyHomeContact': typeof import("../components/Home/Contact.vue")['default']
    'LazyHomeHeader': typeof import("../components/Home/Header.vue")['default']
    'LazyHomeServices': typeof import("../components/Home/Services.vue")['default']
    'LazyHomeTeam': typeof import("../components/Home/Team.vue")['default']
    'LazyHomeTestimonials': typeof import("../components/Home/Testimonials.vue")['default']
    'LazyHomeWorks': typeof import("../components/Home/Works.vue")['default']
    'LazyLandingAbout': typeof import("../components/Landing/About.vue")['default']
    'LazyLandingAccordions': typeof import("../components/Landing/Accordions.vue")['default']
    'LazyLandingBlog': typeof import("../components/Landing/Blog.vue")['default']
    'LazyLandingBrands': typeof import("../components/Landing/Brands.vue")['default']
    'LazyLandingContact': typeof import("../components/Landing/Contact.vue")['default']
    'LazyLandingHeader': typeof import("../components/Landing/Header.vue")['default']
    'LazyLandingMarquee': typeof import("../components/Landing/Marquee.vue")['default']
    'LazyLandingWorks': typeof import("../components/Landing/Works.vue")['default']
    'LazyPortfolioCarouselSlider': typeof import("../components/Portfolio/CarouselSlider.vue")['default']
    'LazyPortfolioFixedText': typeof import("../components/Portfolio/FixedText.vue")['default']
    'LazyPortfolioGrid': typeof import("../components/Portfolio/Grid.vue")['default']
    'LazyPortfolioGridClassic': typeof import("../components/Portfolio/GridClassic.vue")['default']
    'LazyPortfolioHeader': typeof import("../components/Portfolio/Header.vue")['default']
    'LazyPortfolioInteractiveInline': typeof import("../components/Portfolio/InteractiveInline.vue")['default']
    'LazyPortfolioInteractiveVertical': typeof import("../components/Portfolio/InteractiveVertical.vue")['default']
    'LazyPreviewFooter': typeof import("../components/Preview/Footer.vue")['default']
    'LazyPreviewHeader': typeof import("../components/Preview/Header.vue")['default']
    'LazyPreviewNavigation': typeof import("../components/Preview/Navigation.vue")['default']
    'LazyPreviewPortfolio': typeof import("../components/Preview/Portfolio.vue")['default']
    'LazyProjectFourBottomContent': typeof import("../components/Project/Four/BottomContent.vue")['default']
    'LazyProjectFourBottomImage': typeof import("../components/Project/Four/BottomImage.vue")['default']
    'LazyProjectFourHeader': typeof import("../components/Project/Four/Header.vue")['default']
    'LazyProjectFourImageColumn': typeof import("../components/Project/Four/ImageColumn.vue")['default']
    'LazyProjectFourNextProject': typeof import("../components/Project/Four/NextProject.vue")['default']
    'LazyProjectFourTopContent': typeof import("../components/Project/Four/TopContent.vue")['default']
    'LazyProjectOneBottomContent': typeof import("../components/Project/One/BottomContent.vue")['default']
    'LazyProjectOneHeader': typeof import("../components/Project/One/Header.vue")['default']
    'LazyProjectOneNextProject': typeof import("../components/Project/One/NextProject.vue")['default']
    'LazyProjectOneTopContent': typeof import("../components/Project/One/TopContent.vue")['default']
    'LazyProjectOneWorks': typeof import("../components/Project/One/Works.vue")['default']
    'LazyProjectThreeBottomContent': typeof import("../components/Project/Three/BottomContent.vue")['default']
    'LazyProjectThreeBottomImage': typeof import("../components/Project/Three/BottomImage.vue")['default']
    'LazyProjectThreeHeader': typeof import("../components/Project/Three/Header.vue")['default']
    'LazyProjectThreeImageColumn': typeof import("../components/Project/Three/ImageColumn.vue")['default']
    'LazyProjectThreeNextProject': typeof import("../components/Project/Three/NextProject.vue")['default']
    'LazyProjectThreeTopContent': typeof import("../components/Project/Three/TopContent.vue")['default']
    'LazyProjectTwoBottomContent': typeof import("../components/Project/Two/BottomContent.vue")['default']
    'LazyProjectTwoHeader': typeof import("../components/Project/Two/Header.vue")['default']
    'LazyProjectTwoNextProject': typeof import("../components/Project/Two/NextProject.vue")['default']
    'LazyProjectTwoTopContent': typeof import("../components/Project/Two/TopContent.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AboutHeader: typeof import("../components/About/Header.vue")['default']
export const AboutIntro: typeof import("../components/About/Intro.vue")['default']
export const AboutJourney: typeof import("../components/About/Journey.vue")['default']
export const BlogBlogs: typeof import("../components/Blog/Blogs.vue")['default']
export const BlogDetailsAuthorArea: typeof import("../components/Blog/Details/AuthorArea.vue")['default']
export const BlogDetailsCommentsForm: typeof import("../components/Blog/Details/CommentsForm.vue")['default']
export const BlogDetailsContent: typeof import("../components/Blog/Details/Content.vue")['default']
export const BlogDetails: typeof import("../components/Blog/Details/Details.vue")['default']
export const BlogDetailsHeader: typeof import("../components/Blog/Details/Header.vue")['default']
export const BlogDetailsInfoArea: typeof import("../components/Blog/Details/InfoArea.vue")['default']
export const BlogDetailsNextPrev: typeof import("../components/Blog/Details/NextPrev.vue")['default']
export const BlogHeader: typeof import("../components/Blog/Header.vue")['default']
export const CommonCursor: typeof import("../components/Common/Cursor.vue")['default']
export const CommonFooter1: typeof import("../components/Common/Footer1.vue")['default']
export const CommonFooter2: typeof import("../components/Common/Footer2.vue")['default']
export const CommonLoader: typeof import("../components/Common/Loader.vue")['default']
export const CommonMenu: typeof import("../components/Common/Menu.vue")['default']
export const CommonNavbar: typeof import("../components/Common/Navbar.vue")['default']
export const CommonProgressScroll: typeof import("../components/Common/ProgressScroll.vue")['default']
export const ContactForm: typeof import("../components/Contact/Form.vue")['default']
export const ContactHeader: typeof import("../components/Contact/Header.vue")['default']
export const ContactInfo: typeof import("../components/Contact/Info.vue")['default']
export const CreativePortfolioBlog: typeof import("../components/CreativePortfolio/Blog.vue")['default']
export const CreativePortfolioContact: typeof import("../components/CreativePortfolio/Contact.vue")['default']
export const CreativePortfolioHeader: typeof import("../components/CreativePortfolio/Header.vue")['default']
export const CreativePortfolioMarquee: typeof import("../components/CreativePortfolio/Marquee.vue")['default']
export const CreativePortfolioTestimonials: typeof import("../components/CreativePortfolio/Testimonials.vue")['default']
export const HomeAbout: typeof import("../components/Home/About.vue")['default']
export const HomeAwards: typeof import("../components/Home/Awards.vue")['default']
export const HomeContact: typeof import("../components/Home/Contact.vue")['default']
export const HomeHeader: typeof import("../components/Home/Header.vue")['default']
export const HomeServices: typeof import("../components/Home/Services.vue")['default']
export const HomeTeam: typeof import("../components/Home/Team.vue")['default']
export const HomeTestimonials: typeof import("../components/Home/Testimonials.vue")['default']
export const HomeWorks: typeof import("../components/Home/Works.vue")['default']
export const LandingAbout: typeof import("../components/Landing/About.vue")['default']
export const LandingAccordions: typeof import("../components/Landing/Accordions.vue")['default']
export const LandingBlog: typeof import("../components/Landing/Blog.vue")['default']
export const LandingBrands: typeof import("../components/Landing/Brands.vue")['default']
export const LandingContact: typeof import("../components/Landing/Contact.vue")['default']
export const LandingHeader: typeof import("../components/Landing/Header.vue")['default']
export const LandingMarquee: typeof import("../components/Landing/Marquee.vue")['default']
export const LandingWorks: typeof import("../components/Landing/Works.vue")['default']
export const PortfolioCarouselSlider: typeof import("../components/Portfolio/CarouselSlider.vue")['default']
export const PortfolioFixedText: typeof import("../components/Portfolio/FixedText.vue")['default']
export const PortfolioGrid: typeof import("../components/Portfolio/Grid.vue")['default']
export const PortfolioGridClassic: typeof import("../components/Portfolio/GridClassic.vue")['default']
export const PortfolioHeader: typeof import("../components/Portfolio/Header.vue")['default']
export const PortfolioInteractiveInline: typeof import("../components/Portfolio/InteractiveInline.vue")['default']
export const PortfolioInteractiveVertical: typeof import("../components/Portfolio/InteractiveVertical.vue")['default']
export const PreviewFooter: typeof import("../components/Preview/Footer.vue")['default']
export const PreviewHeader: typeof import("../components/Preview/Header.vue")['default']
export const PreviewNavigation: typeof import("../components/Preview/Navigation.vue")['default']
export const PreviewPortfolio: typeof import("../components/Preview/Portfolio.vue")['default']
export const ProjectFourBottomContent: typeof import("../components/Project/Four/BottomContent.vue")['default']
export const ProjectFourBottomImage: typeof import("../components/Project/Four/BottomImage.vue")['default']
export const ProjectFourHeader: typeof import("../components/Project/Four/Header.vue")['default']
export const ProjectFourImageColumn: typeof import("../components/Project/Four/ImageColumn.vue")['default']
export const ProjectFourNextProject: typeof import("../components/Project/Four/NextProject.vue")['default']
export const ProjectFourTopContent: typeof import("../components/Project/Four/TopContent.vue")['default']
export const ProjectOneBottomContent: typeof import("../components/Project/One/BottomContent.vue")['default']
export const ProjectOneHeader: typeof import("../components/Project/One/Header.vue")['default']
export const ProjectOneNextProject: typeof import("../components/Project/One/NextProject.vue")['default']
export const ProjectOneTopContent: typeof import("../components/Project/One/TopContent.vue")['default']
export const ProjectOneWorks: typeof import("../components/Project/One/Works.vue")['default']
export const ProjectThreeBottomContent: typeof import("../components/Project/Three/BottomContent.vue")['default']
export const ProjectThreeBottomImage: typeof import("../components/Project/Three/BottomImage.vue")['default']
export const ProjectThreeHeader: typeof import("../components/Project/Three/Header.vue")['default']
export const ProjectThreeImageColumn: typeof import("../components/Project/Three/ImageColumn.vue")['default']
export const ProjectThreeNextProject: typeof import("../components/Project/Three/NextProject.vue")['default']
export const ProjectThreeTopContent: typeof import("../components/Project/Three/TopContent.vue")['default']
export const ProjectTwoBottomContent: typeof import("../components/Project/Two/BottomContent.vue")['default']
export const ProjectTwoHeader: typeof import("../components/Project/Two/Header.vue")['default']
export const ProjectTwoNextProject: typeof import("../components/Project/Two/NextProject.vue")['default']
export const ProjectTwoTopContent: typeof import("../components/Project/Two/TopContent.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyAboutHeader: typeof import("../components/About/Header.vue")['default']
export const LazyAboutIntro: typeof import("../components/About/Intro.vue")['default']
export const LazyAboutJourney: typeof import("../components/About/Journey.vue")['default']
export const LazyBlogBlogs: typeof import("../components/Blog/Blogs.vue")['default']
export const LazyBlogDetailsAuthorArea: typeof import("../components/Blog/Details/AuthorArea.vue")['default']
export const LazyBlogDetailsCommentsForm: typeof import("../components/Blog/Details/CommentsForm.vue")['default']
export const LazyBlogDetailsContent: typeof import("../components/Blog/Details/Content.vue")['default']
export const LazyBlogDetails: typeof import("../components/Blog/Details/Details.vue")['default']
export const LazyBlogDetailsHeader: typeof import("../components/Blog/Details/Header.vue")['default']
export const LazyBlogDetailsInfoArea: typeof import("../components/Blog/Details/InfoArea.vue")['default']
export const LazyBlogDetailsNextPrev: typeof import("../components/Blog/Details/NextPrev.vue")['default']
export const LazyBlogHeader: typeof import("../components/Blog/Header.vue")['default']
export const LazyCommonCursor: typeof import("../components/Common/Cursor.vue")['default']
export const LazyCommonFooter1: typeof import("../components/Common/Footer1.vue")['default']
export const LazyCommonFooter2: typeof import("../components/Common/Footer2.vue")['default']
export const LazyCommonLoader: typeof import("../components/Common/Loader.vue")['default']
export const LazyCommonMenu: typeof import("../components/Common/Menu.vue")['default']
export const LazyCommonNavbar: typeof import("../components/Common/Navbar.vue")['default']
export const LazyCommonProgressScroll: typeof import("../components/Common/ProgressScroll.vue")['default']
export const LazyContactForm: typeof import("../components/Contact/Form.vue")['default']
export const LazyContactHeader: typeof import("../components/Contact/Header.vue")['default']
export const LazyContactInfo: typeof import("../components/Contact/Info.vue")['default']
export const LazyCreativePortfolioBlog: typeof import("../components/CreativePortfolio/Blog.vue")['default']
export const LazyCreativePortfolioContact: typeof import("../components/CreativePortfolio/Contact.vue")['default']
export const LazyCreativePortfolioHeader: typeof import("../components/CreativePortfolio/Header.vue")['default']
export const LazyCreativePortfolioMarquee: typeof import("../components/CreativePortfolio/Marquee.vue")['default']
export const LazyCreativePortfolioTestimonials: typeof import("../components/CreativePortfolio/Testimonials.vue")['default']
export const LazyHomeAbout: typeof import("../components/Home/About.vue")['default']
export const LazyHomeAwards: typeof import("../components/Home/Awards.vue")['default']
export const LazyHomeContact: typeof import("../components/Home/Contact.vue")['default']
export const LazyHomeHeader: typeof import("../components/Home/Header.vue")['default']
export const LazyHomeServices: typeof import("../components/Home/Services.vue")['default']
export const LazyHomeTeam: typeof import("../components/Home/Team.vue")['default']
export const LazyHomeTestimonials: typeof import("../components/Home/Testimonials.vue")['default']
export const LazyHomeWorks: typeof import("../components/Home/Works.vue")['default']
export const LazyLandingAbout: typeof import("../components/Landing/About.vue")['default']
export const LazyLandingAccordions: typeof import("../components/Landing/Accordions.vue")['default']
export const LazyLandingBlog: typeof import("../components/Landing/Blog.vue")['default']
export const LazyLandingBrands: typeof import("../components/Landing/Brands.vue")['default']
export const LazyLandingContact: typeof import("../components/Landing/Contact.vue")['default']
export const LazyLandingHeader: typeof import("../components/Landing/Header.vue")['default']
export const LazyLandingMarquee: typeof import("../components/Landing/Marquee.vue")['default']
export const LazyLandingWorks: typeof import("../components/Landing/Works.vue")['default']
export const LazyPortfolioCarouselSlider: typeof import("../components/Portfolio/CarouselSlider.vue")['default']
export const LazyPortfolioFixedText: typeof import("../components/Portfolio/FixedText.vue")['default']
export const LazyPortfolioGrid: typeof import("../components/Portfolio/Grid.vue")['default']
export const LazyPortfolioGridClassic: typeof import("../components/Portfolio/GridClassic.vue")['default']
export const LazyPortfolioHeader: typeof import("../components/Portfolio/Header.vue")['default']
export const LazyPortfolioInteractiveInline: typeof import("../components/Portfolio/InteractiveInline.vue")['default']
export const LazyPortfolioInteractiveVertical: typeof import("../components/Portfolio/InteractiveVertical.vue")['default']
export const LazyPreviewFooter: typeof import("../components/Preview/Footer.vue")['default']
export const LazyPreviewHeader: typeof import("../components/Preview/Header.vue")['default']
export const LazyPreviewNavigation: typeof import("../components/Preview/Navigation.vue")['default']
export const LazyPreviewPortfolio: typeof import("../components/Preview/Portfolio.vue")['default']
export const LazyProjectFourBottomContent: typeof import("../components/Project/Four/BottomContent.vue")['default']
export const LazyProjectFourBottomImage: typeof import("../components/Project/Four/BottomImage.vue")['default']
export const LazyProjectFourHeader: typeof import("../components/Project/Four/Header.vue")['default']
export const LazyProjectFourImageColumn: typeof import("../components/Project/Four/ImageColumn.vue")['default']
export const LazyProjectFourNextProject: typeof import("../components/Project/Four/NextProject.vue")['default']
export const LazyProjectFourTopContent: typeof import("../components/Project/Four/TopContent.vue")['default']
export const LazyProjectOneBottomContent: typeof import("../components/Project/One/BottomContent.vue")['default']
export const LazyProjectOneHeader: typeof import("../components/Project/One/Header.vue")['default']
export const LazyProjectOneNextProject: typeof import("../components/Project/One/NextProject.vue")['default']
export const LazyProjectOneTopContent: typeof import("../components/Project/One/TopContent.vue")['default']
export const LazyProjectOneWorks: typeof import("../components/Project/One/Works.vue")['default']
export const LazyProjectThreeBottomContent: typeof import("../components/Project/Three/BottomContent.vue")['default']
export const LazyProjectThreeBottomImage: typeof import("../components/Project/Three/BottomImage.vue")['default']
export const LazyProjectThreeHeader: typeof import("../components/Project/Three/Header.vue")['default']
export const LazyProjectThreeImageColumn: typeof import("../components/Project/Three/ImageColumn.vue")['default']
export const LazyProjectThreeNextProject: typeof import("../components/Project/Three/NextProject.vue")['default']
export const LazyProjectThreeTopContent: typeof import("../components/Project/Three/TopContent.vue")['default']
export const LazyProjectTwoBottomContent: typeof import("../components/Project/Two/BottomContent.vue")['default']
export const LazyProjectTwoHeader: typeof import("../components/Project/Two/Header.vue")['default']
export const LazyProjectTwoNextProject: typeof import("../components/Project/Two/NextProject.vue")['default']
export const LazyProjectTwoTopContent: typeof import("../components/Project/Two/TopContent.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
